### ISSUE TITLE
How to handle errors?

### ISSUE THREAD

**Issue by waeljammal** [saantiaguilera/go-pipeline#10]
Hi, nice library but I have a question, short of wrapping stages with lifecycle then kicking off another flow is there a cleaner way to handle error branches so they can also be included in the generated svg? As it stands my UML is incomplete because it does not show error paths. Using tags and context is awkward for error handling as well because it requires a lot of extra logic and wrapping of conditional groups at different steps to check for errors.

**Comment by saantiaguilera** [comment]
How would you imagine creating and visualizing error branches with the current API? As far as I'm understanding, this is not supported out of the box with the current implementations (you can wrap it in a lifecycle using it as a "fallback" maybe?).

I guess the best way to do this is to create your own custom Stage that handles it, something along the lines of:
```go
type stageImpl struct {
    stage Stage
    errorStage Stage
}

func (s *stageImpl) Draw(graph GraphDiagram) {
    // Draw as you imagine the graph for this
}

func (s *stageImpl) Run(executor Executor, ctx Context) error {
    if err := l.stage.Run(executor, ctx); err != nil {
        return l.errorStage.Run(executor, ctx)
    }
    return nil
}

func CreateStageImpl(stage Stage, errorStage Stage) Stage {
    return &stageImpl{
        stage: stage,
        errorStage: errorStage,
    }
}
```

**Comment by saantiaguilera** [comment]
While this is not supported through the barebone API because is a niche case, the contract is flexible enough to now allow it transparently through custom made steps.

I've provided some examples of this specific scenario [here](https://github.com/saantiaguilera/go-pipeline/tree/master/examples/customsteps) under the 'fallbackXYZ' name
