### ISSUE TITLE
Playing with it

### ISSUE THREAD

**Issue by marcelloh** [saantiaguilera/go-pipeline#9]
I have several questions.

1. recreate svg
For what I understood, the program also makes the svg. But when I rename an example one, it doesn't recreate that. Did I misunderstood?

2. read form config (like toml)
What if I could set up a pipeline via some config file. I would be able to build all the possibilities that I want, but have  that config-file that will use only the parts needed.
Let's say, I build a CRM but my customers have different wishes after a new user registers. I could then easily have them pick some predefined config (or even have them by themselves) That would mean that it's going to behave more like BPML (Perhaps even read that to drive the pipeline). I see a lot of possibilities here.

**Comment by saantiaguilera** [comment]
Hey!
1. Check I’m using a flag to avoid creating it on all builds (-pipeline.render if I’m not mistaken). This is to avoid on each CI run to render the SVGs. It’s on the first line of code so you can even stub it with “if true” and it should work
2. Gonna check it out! I like the idea :)

**Comment by saantiaguilera** [comment]
Hey, I've given some thought into this. The API is already auto-sufficient in its high-level declarative structure, adding decorations to this (eg. TOML style configs you mention) would be nice as external packages, so the API doesn't get too rigid + the ones who want that can consume it specifically

Given this thought, I will probably move the UMLActivity implementation as an outside package, as this also applies.
